### ISSUE TITLE
License is missing

### ISSUE THREAD

**Issue by lancedikson** [a-h/githubbackup#2]
Hi! Thanks for open-sourcing the repo! I was considering using it, though the license is not published here, so by default it should be very restrictive, which is not an optimal case for many users. Would you mind adding a license statement to the package so that its usage terms are clear for the community? Thanks! 🙏

**Comment by a-h** [comment]
I've added an MIT license.

**Comment by lancedikson** [comment]
Thank you! Appreciate quick reaction! 🙏
